<?php
/**
 * @file
 * Code for the Luggage Blog feature.
 */

include_once 'luggage_blog.features.inc';

/**
 * Implements theme_preprocess_node()
 */
function luggage_blog_preprocess_node(&$vars) {
  // Rewrite the display of the "Display author and date information" to be nicer for only
  // blog posts.
  if ($vars['submitted'] && $vars['type'] == "lug_blog") {
    // Search results and teasers: February 25, 2016 
    if ($vars['teaser'] || $vars['view_mode'] == 'search_result') {
      $vars['submitted'] = t("%datetime",
        array('%datetime' => format_date($vars['node']->created, 'custom', 'F j, Y')));
    }
    else {
      // Otherwise use the format defined by luggage_news
      $vars['submitted'] = t("%datetime",
        array('%datetime' => format_date($vars['node']->created, 'news')));
    }
  }
}
